[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.0"
bson = "2.6.1"
mongodb = "2.5.0"
quote = "1.0.26"
syn = "2.0.15"
