[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.17"
reqwest = "0.11.18"
rocket = "=0.5.0-rc.3"
scraper = "0.16.0"
