name: APP Unit tests
on: 
  push:
  pull_request:
    branches:
      - main
      - dev
      
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        working-directory: ./app/WhereIsThePower
        run: npm install --frozen-lock
      - name: Run Tests
        working-directory: ./app/WhereIsThePower
        run: npm run test