name: APP Unit tests
on: 
  push:
  pull_request:
    branches:
      - main
      - dev
      
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        working-directory: ./app/WhereIsThePower
        run: npm install --frozen-lock
      - name: Update env
        working-directory: ./app/WhereIsThePower/src/environments
        run: |
          > environment.ts
          echo export const environment = { >> environment.ts
          echo production: false, >> environment.ts
          echo googleMapsApiKey: >> environment.ts
          ${{secrets.TEST_SECRET}} >> environment.ts
          echo }; >> environment.ts
      - name: Run Tests
        working-directory: ./app/WhereIsThePower
        run: npm run test
