name: Build and test API

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
        API_PUBLIC_KEY: ${{ secrets.API_PUBLIC_KEY }}
      run: cd api && echo $API_PRIVATE_KEY > privateKey.pem && echo $API_PUBLIC_KEY > publicKey.pem && cargo build --verbose
    - name: Run tests
      env:
        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
        API_PUBLIC_KEY: ${{ secrets.API_PUBLIC_KEY }}
      run: cd api && echo $API_PRIVATE_KEY > privateKey.pem && echo $API_PUBLIC_KEY > publicKey.pem && cargo test --verbose
